version: "3.7"
services:
  mongo:
    image: mongo
    ports:
      - 27017-27019:27017
    restart: always
    command: /usr/bin/mongod --bind_ip_all --replSet rs0
  uservice:
    build: persistence-service
    ports:
      - 3000-3002:3000
    depends_on: 
      - mongo
    restart: always
  redis:
    image: redis
    container_name: cache
    ports:
      - 6379:6379
